### ISSUE TITLE
Game crashes on script reload

### ISSUE THREAD

**Issue by oldnapalm** [Sardelka9515/scripthookvdotnetcore#8]
When I press Home to reload the scripts (RAGECOOP) the game crashes.

```
Nome do aplicativo com falha: GTA5.exe, versão: 1.0.2845.0, carimbo de data/hora: 0x63ee4cf2
Nome do módulo com falha: clr.dll, versão: 4.8.4614.0, carimbo de data/hora: 0x63995bc5
Código de exceção: 0xc00000fd
Deslocamento da falha: 0x0000000000682e80
ID do processo com falha: 0x540
Hora de início do aplicativo com falha: 0x01d971358b206d84
Caminho do aplicativo com falha: D:\Grand Theft Auto V\GTA5.exe
Caminho do módulo com falha: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
```

Crash also occurs when a client resource is loaded (Race). Tried with `SkipLegalScreen=false` but no difference.

**Comment by Sardelka9515** [comment]
Might be related to #3, can you try this SHVDN build?
https://ci.appveyor.com/project/crosire/scripthookvdotnet/builds/46789821/artifacts

**Comment by oldnapalm** [comment]
Yes, using this build the game doesn't crash.

The client resource still fails but I guess it's another issue.

```
[22:47:46] [error] Failed to register script RageCoop.Resources.Race.Main
[22:47:46] [error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RageCoop.Client.Scripting.ClientScript.<.ctor>b__2_0(ClientFile x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at RageCoop.Client.Scripting.ClientScript..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at SHVDN.Core.FindAndRegisterAllScripts() in M:\SandBox-Shared\repos\RAGECOOP\RAGECOOP-V\libs\ScriptHookVDotNetCore\src\ScriptHookVDotNetCore\Core.CLR.cs:line 255
```

**Comment by oldnapalm** [comment]
The resource error was my mistake, I didn't rebuild the resource builder before building the resource.

**Comment by yamin8000** [comment]
@oldnapalm I don't know how to provide meaningful logs but I have the same issue. The game crashed when I was trying to reload scripts.  
```
[21:55:10] [info] Unloading scripts in F:\Grand Theft Auto V\CoreScripts
[21:55:10] [debug] Thread stopped: vScriptTest.TestScript
[21:55:10] [info] Unloaded scripts in F:\Grand Theft Auto V\CoreScripts
```

**Comment by oldnapalm** [comment]
> @oldnapalm I don't know how to provide meaningful logs but I have the same issue. The game crashed when I was trying to reload scripts.

In my case it was because I had the release version of SHVDN. It works using the latest build from https://github.com/scripthookvdotnet/scripthookvdotnet/actions/workflows/build.yml

Click on the latest workflow then download "ScriptHookVDotNet" under "Artifacts".

**Comment by yamin8000** [comment]
> > @oldnapalm I don't know how to provide meaningful logs but I have the same issue. The game crashed when I was trying to reload scripts.
> 
> In my case it was because I had the release version of SHVDN. It works using the latest build from https://github.com/scripthookvdotnet/scripthookvdotnet/actions/workflows/build.yml
> 
> Click on the latest workflow then download "ScriptHookVDotNet" under "Artifacts".

Thank you. I was going to download the .NET Framework to try scripting with that. I'll try the latest build artifact.
